server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: "ms-generic-auth-java"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    tasks: "/api/v1/usuarios"
adapters:
  r2dbc:
    host: "172.17.7.189"
    port: 5432
    database: "authdb"
    schema: "auth"
    username: "root"
    password: "root"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  issuer: "clean-arch-demo"
  audience: "security-api"
  access-token-seconds: 900
  refresh-token-seconds: 1209600
  rsa:
    public: "classpath:keys/public.pem"
    private: "classpath:keys/private.pem"


